INSERT INTO
	"public"."users" (
		"id",
		"email",
		"password",
		"created_at",
		"updated_at"
	)
VALUES
	(
		1,
		'hoadirector.dev@gmail.com',
		'anything',
		current_timestamp(2),
		current_timestamp(2)
	)

INSERT INTO
	"public"."system_roles" ("user_id", "role_id", "created_at", "updated_at")
VALUES
	(1, 99, current_timestamp(2), current_timestamp(2))

INSERT INTO
	"public"."home_owner_associations" ("name", "created_at", "updated_at")
VALUES
	('South Pointe', current_timestamp(2), current_timestamp(2))


UPDATE "public"."home_owner_associations" SET "created_at"=current_timestamp(2), "updated_at"=current_timestamp(2)  WHERE "id"=1 RETURNING "id", "name", "created_at", "updated_at", "deleted_at";